import type { NextPage } from 'next'
import Head from 'next/head'
import ContactSocial from '../components/ContactSocial/ContactSocial'
import Header from '../components/Header/Header'
import Intro from '../components/Intro/Intro'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Elionai Melo </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='px-10'>
        <Intro />
        <ContactSocial />
      </main>
    </>
  )
}

export default Home
